---
version: '2.4'

services:
  case-payment-orders-api:
    image: "hmctspublic.azurecr.io/cpo/case-payment-orders-api:latest"
    container_name: case-payment-orders-api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://cpo-db:5432/cpo
      CPO_S2S_AUTHORISED_SERVICES: xui_webapp
      IDAM_OIDC_URL: https://idam-web-public.aat.platform.hmcts.net
      IDAM_API_URL: https://idam-api.aat.platform.hmcts.net
      S2S_URL: http://rpe-service-auth-provider-aat.service.core-compute-aat.internal
    ports:
      - 4457:4457
    depends_on:
      - cpo-db

  cpo-db:
    image: postgres:11.11
    restart: always
    environment:
      - POSTGRES_DB=cpo
      - POSTGRES_USER=cpo
      - POSTGRES_PASSWORD=cpo
    ports:
      - 5678:5432
    volumes:
      - cpo-database-data:/var/lib/postgresql/data

volumes:
  cpo-database-data:
