server:
  port: 4457

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus

#If you use a database then uncomment below lines and update db properties accordingly
spring:
  config:
    import: "optional:configtree:/mnt/secrets/cpo"
  application:
    name: Case Payment Orders
  jackson:
    property-naming-strategy: SNAKE_CASE
  main:
    allow-bean-definition-overriding: true
  cache:
    cache-names: userInfoCache
    caffeine:
      spec: expireAfterAccess=1800s
  datasource:
    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}${DB_OPTIONS:}
#    username: ${DB_USER_NAME}
#    password: ${DB_PASSWORD}
#    properties:
#      charSet: UTF-8
#    hikari:
#      minimumIdle: 2
#      maximumPoolSize: 10
#      idleTimeout: 10000
#      poolName: {to-be-defined}HikariCP
#      maxLifetime: 7200000
#      connectionTimeout: 30000
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
#          lob:
#            # silence the 'wall-of-text' - unnecessary exception throw about blob types
#            non_contextual_creation: true
  security:
    oauth2:
      client:
        provider:
          oidc:
            issuer-uri: ${IDAM_OIDC_URL:http://localhost:5000}/o
        registration:
          oidc:
            client-id: internal
            client-secret: internal
idam:
  api:
    url: ${IDAM_API_URL:http://localhost:5000}
  s2s-auth:
    url: ${S2S_URL:http://localhost:4502}
  s2s-authorised:
    services: ${CPO_S2S_AUTHORISED_SERVICES:xui_webapp}
oidc:
  issuer: ${OIDC_ISSUER:http://fr-am:8080/openam/oauth2/hmcts}

azure:
  application-insights:
    instrumentation-key: ${cpo.AppInsightsInstrumentationKey:00000000-0000-0000-0000-000000000000}
