server:
  port: 4457

management:
  endpoint:
    health:
      show-details: "always"
      cache:
        time-to-live: 1000ms
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus
  health:
    probes:
      enabled: true
spring:
  application:
    name: Case Payment Orders
  banner:
    location: classpath:case-payment-orders-banner.txt
  cloud:
    discovery:
      client:
        composite-indicator:
          enabled: false
  config:
    import: "optional:configtree:/mnt/secrets/cpo/"
  jackson:
    property-naming-strategy: SNAKE_CASE
  main:
    allow-bean-definition-overriding: true
  cache:
    cache-names: userInfoCache
    caffeine:
      spec: expireAfterAccess=1800s
  data:
    web:
      pageable:
        max-page-size: 20
        default-page-size: 20
        one-indexed-parameters: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${CPO_CASE_PAYMENT_ORDERS_DB_HOST:localhost}:${CPO_CASE_PAYMENT_ORDERS_DB_PORT:6968}/${CPO_CASE_PAYMENT_ORDERS_DB_NAME:cpo_case_payment_orders}${CPO_CASE_PAYMENT_ORDERS_DB_OPTIONS:}
    username: ${CPO_CASE_PAYMENT_ORDERS_DB_USERNAME:cpo}
    password: ${CPO_CASE_PAYMENT_ORDERS_DB_PASSWORD:cpo}
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    database: postgresql
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
      org:
        hibernate:
          envers:
            audit_table_suffix: _audit
            store_data_at_delete: true

  flyway:
    out-of-order: true
    ignore-missing-migrations: true
  security:
    oauth2:
      client:
        provider:
          oidc:
            issuer-uri: ${IDAM_OIDC_URL:http://localhost:5000}/o
        registration:
          oidc:
            client-id: internal
            client-secret: internal


idam:
  api:
    url: ${IDAM_API_URL:http://localhost:5000}
  s2s-auth:
    url: ${S2S_URL:http://localhost:4502}
  s2s-authorised:
    services: ${CPO_S2S_AUTHORISED_SERVICES:xui_webapp,payment_app}
oidc:
  issuer: ${OIDC_ISSUER:http://fr-am:8080/openam/oauth2/hmcts}

azure:
  application-insights:
    instrumentation-key: ${cpo.AppInsightsInstrumentationKey:00000000-0000-0000-0000-000000000000}

s2s:
  authorizations:
    payment:
      id: "payment_app"
      permission: "R"
    xui:
      id: "xui_webapp"
      permission: "CRUD"