server:
  port: 4457

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus

spring:
  config:
    import: "optional:configtree:/mnt/secrets/"
  application:
    name: Case Payment Orders API
  datasource:
    url: jdbc:postgresql://${CPO_CASE_PAYMENT_ORDERS_DB_HOST:localhost}:${CPO_CASE_PAYMENT_ORDERS_DB_PORT:6968}/${CPO_CASE_PAYMENT_ORDERS_DB_NAME:cpo_case_payment_orders}${CPO_CASE_PAYMENT_ORDERS_DB_OPTIONS:}
    username: ${CPO_CASE_PAYMENT_ORDERS_DB_USERNAME:cpo}
    password: ${CPO_CASE_PAYMENT_ORDERS_DB_PASSWORD:cpo}
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    database: postgresql
    show-sql: false
    hibernate:
      ddl-auto: none
  flyway:
    baseline-on-migrate: true
    baseline-version: 0001
    out-of-order: true
    ignore-missing-migrations: true

flyway:
  noop:
    strategy: ${FLYWAY_NOOP_STRATEGY:false}

azure:
  application-insights:
    instrumentation-key: ${cpo.AppInsightsInstrumentationKey:00000000-0000-0000-0000-000000000000}
