name: Add a Dummy commit to trigger dev build

#on:
#  schedule:
#    - cron: "30 13 * * *"
on:
  push:
    branches:
      - CCD-3916_Github_Actions
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
        with:
          ref: develop

      - name: Push Dummy Commit to develop branch
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          skip_dirty_check: true
          commit_message: "Trigger build"
          commit_options: "--allow-empty"
          branch: 'develop'
